return {
    {item = "latex", icon = nil, stage = 1, icon_size = 64},
    {item = "biomass", icon = nil, stage = 1, icon_size = 64},
    {item = "agar", icon = nil, stage = 1, icon_size = 64},
    {item = "cellulose", icon = nil, stage = 1, icon_size = 64},
    {item = "latex-slab", icon = nil, stage = 1, icon_size = 64},
    {item = "moss", icon = nil, stage = 1, icon_size = 64, type = "module"},
    {item = "empty-comb", icon = nil, stage = 1, icon_size = 64},
    {item = "saps", icon = nil, stage = 1, icon_size = 64},
    {item = "moss-gen", icon = nil, stage = 1, icon_size = 64},
    {item = "bio-sample", icon = nil, stage = 1, icon_size = 64},
    {item = "cdna", icon = nil, stage = 1, icon_size = 64},
    {item = "plasmids", icon = nil, stage = 1, icon_size = 64},
    {item = "retrovirus", icon = nil, stage = 1, icon_size = 64},
    {item = "sodium-alginate", icon = nil, stage = 1, icon_size = 64},
    {item = "petri-dish", icon = nil, stage = 1, icon_size = 64},
    {item = "petri-dish-bacteria", icon = nil, stage = 1, icon_size = 64},
    {item = "cocoon", icon = nil, stage = 1, icon_size = 64},
    {item = "seaweed", icon = nil, stage = 1, icon_size = 64, type = "module"},
    {item = "wood-seeds", icon = nil, stage = 1, icon_size = 64},
    {item = "moondrop-seeds", icon = nil, stage = 1, icon_size = 64},
    {item = "fungal-substrate", icon = nil, stage = 1, icon_size = 64},
    {item = "meat", icon = nil, stage = 1, icon_size = 64},
    {item = "dried-meat", icon = nil, stage = 1, icon_size = 64, type = "capsule"},
    {item = "mukmoux-fat", icon = nil, stage = 1, icon_size = 64, inFinalFixes = true},
    {item = "brain", icon = nil, stage = 1, icon_size = 64},
    {item = "guts", icon = nil, stage = 1, icon_size = 64},
    {item = "caged-auog", icon = nil, stage = 1, icon_size = 64},
    {item = "caged-vrauks", icon = nil, stage = 1, icon_size = 64},
    {item = "sap-seeds", icon = nil, stage = 1, icon_size = 64},
    {item = "kicalk-seeds", icon = nil, stage = 1, icon_size = 64},
    {item = "wood-seedling", icon = nil, stage = 1, icon_size = 64},
    {item = "ralesias", icon = nil, stage = 1, icon_size = 64, type = "module", inFinalFixes = true},
    {item = "guar", icon = nil, stage = 1, icon_size = 64, type = "module", inFinalFixes = true},
    {item = "arthurian-food-01", icon = nil, stage = 1, icon_size = 64},
    {item = "auog-food-01", icon = nil, stage = 1, icon_size = 64},
    {item = "cottongut-food-01", icon = nil, stage = 1, icon_size = 64},
    {item = "dhilmos-food-01", icon = nil, stage = 1, icon_size = 64},
    {item = "dingrits-food-01", icon = nil, stage = 1, icon_size = 64},
    {item = "phagnot-food-01", icon = nil, stage = 1, icon_size = 64},
    {item = "ulric-food-01", icon = nil, stage = 1, icon_size = 64},
    {item = "vrauks-food-01", icon = nil, stage = 1, icon_size = 64},
    {item = "zipir-food-01", icon = nil, stage = 1, icon_size = 64},
    {item = "primers", icon = nil, stage = 1, icon_size = 64},
    {item = "bio-scafold", icon = nil, stage = 1, icon_size = 64},
    {item = "bio-container", icon = nil, stage = 1, icon_size = 64},
    {item = "manure", icon = nil, stage = 1, icon_size = 64},
    {item = "moondrop", icon = nil, stage = 1, icon_size = 64, type = "module"},
    {item = "empty-petri-dish", icon = nil, stage = 1, icon_size = 64},
    {item = "native-flora", icon = nil, stage = 1, icon_size = 64},
    {item = "chitin", icon = nil, stage = 1, icon_size = 64},
    {item = "fungal-substrate-02", icon = nil, stage = 2, icon_size = 64},
    {item = "casein", icon = nil, stage = 2, icon_size = 64},
    {item = "lignin", icon = nil, stage = 2, icon_size = 64},
    {item = "fungal-substrate-03", icon = nil, stage = 2, icon_size = 64},
    {item = "mosfet", icon = nil, stage = 2, icon_size = 64},
    {item = "nisi", icon = nil, stage = 2, icon_size = 64},
    {item = "sic", icon = nil, stage = 2, icon_size = 64},
    {item = "green-sic", icon = nil, stage = 2, icon_size = 64},
    {item = "cobalt-fluoride", icon = nil, stage = 2, icon_size = 64},
    {item = "caged-ulric", icon = nil, stage = 2, icon_size = 64},
    {item = "caged-mukmoux", icon = nil, stage = 2, icon_size = 64},
    {item = "caged-kmauts", icon = nil, stage = 2, icon_size = 64},
    {item = "caged-phagnot", icon = nil, stage = 2, icon_size = 64},
    {item = "caged-korlex", icon = nil, stage = 2, icon_size = 64},
    {item = "fertilizer", icon = nil, icon_size = 64, tech = "fertilizer-mk01", inFinalFixes = true},
    {item = "yotoi-seeds", icon = nil, stage = 2, icon_size = 64},
    {item = "tuuphra-seeds", icon = nil, stage = 2, icon_size = 64},
    {item = "grod-seeds", icon = nil, stage = 2, icon_size = 64},
    {item = "cadaveric-arum-seeds", icon = nil, stage = 2, icon_size = 64},
    {item = "seeds-extract-01", icon = nil, stage = 2, icon_size = 64},
    {item = "arthurian-food-02", icon = nil, stage = 2, icon_size = 64},
    {item = "auog-food-02", icon = nil, stage = 2, icon_size = 64},
    {item = "cottongut-food-02", icon = nil, stage = 2, icon_size = 64},
    {item = "dhilmos-food-02", icon = nil, stage = 2, icon_size = 64},
    {item = "dingrits-food-02", icon = nil, stage = 2, icon_size = 64},
    {item = "fish-food-01", icon = nil, stage = 2, icon_size = 64},
    {item = "korlex-food-01", icon = nil, stage = 2, icon_size = 64},
    {item = "mukmoux-food-01", icon = nil, stage = 2, icon_size = 64},
    {item = "phagnot-food-02", icon = nil, stage = 2, icon_size = 64},
    {item = "ulric-food-02", icon = nil, stage = 2, icon_size = 64},
    {item = "vrauks-food-02", icon = nil, stage = 2, icon_size = 64},
    {item = "zipir-food-02", icon = nil, stage = 2, icon_size = 64},
    {item = "yaedols-spores", icon = nil, stage = 2, icon_size = 64},
    {item = "yaedols", icon = nil, stage = 2, icon_size = 64, type = "module"},
    {item = "arthurian-egg", icon = nil, stage = 2, icon_size = 64},
    {item = "microcin-j25", icon = nil, stage = 2, icon_size = 64},
    {item = "chimeric-proteins", icon = nil, stage = 2, icon_size = 64},
    {item = "cytostatics", icon = nil, stage = 2, icon_size = 64},
    {item = "purine-analogues", icon = nil, stage = 2, icon_size = 64},
    {item = "dingrit-spike", icon = nil, stage = 2, icon_size = 64},
    {item = "propeptides", icon = nil, stage = 2, icon_size = 64},
    {item = "pacifastin", icon = nil, stage = 2, icon_size = 64},
    {item = "immunosupressants", icon = nil, stage = 2, icon_size = 64},
    {item = "pineal-gland", icon = nil, stage = 2, icon_size = 64},
    {item = "magnetic-beads", icon = nil, stage = 2, icon_size = 64},
    {item = "cbp", icon = nil, stage = 2, icon_size = 64},
    {item = "sugar", icon = nil, stage = 2, icon_size = 64},
    {item = "venon-gland", icon = nil, stage = 2, icon_size = 64},
    {item = "alien-enzymes", icon = nil, stage = 2, icon_size = 64},
    {item = "pesticide-mk01", icon = nil, stage = 2, icon_size = 64},
    {item = "pesticide-mk02", icon = nil, stage = 2, icon_size = 64},
    {item = "sea-sponge-sprouts", icon = nil, stage = 2, icon_size = 64},
    {item = "sea-sponge", icon = nil, stage = 2, icon_size = 64, type = "module"},
    {item = "rennea", icon = nil, stage = 2, icon_size = 64, type = "module"},
    {item = "tuuphra", icon = nil, stage = 2, icon_size = 64, type = "module"},
    {item = "bhoddos", icon = nil, stage = 2, icon_size = 64, type = "module"},
    {item = "navens", icon = nil, stage = 2, icon_size = 64, type = "module"},
    {item = "empty-barrel-milk", icon = nil, stage = 2, icon_size = 64},
    {item = "barrel-milk", icon = nil, stage = 2, icon_size = 64},
    {item = "navens-spore", icon = nil, stage = 2, icon_size = 64},
    {item = "co-sulfate", icon = nil, stage = 3, icon_size = 64},
    {item = "co-sulfate-02", icon = nil, stage = 3, icon_size = 64},
    {item = "carapace", icon = nil, stage = 3, icon_size = 64},
    {item = "cobalt-extract", icon = nil, stage = 3, icon_size = 64},
    {item = "cobalt-nx", icon = nil, stage = 3, icon_size = 64},
    {item = "cobalt-oxide", icon = nil, stage = 3, icon_size = 64},
    {item = "neuromorphic-chip", icon = nil, stage = 3, icon_size = 64},
    {item = "metallic-glass", icon = nil, stage = 3, icon_size = 64},
    {item = "caged-arthurian", icon = nil, stage = 3, icon_size = 64},
    {item = "caged-scrondrix", icon = nil, stage = 3, icon_size = 64},
    {item = "caged-phadai", icon = nil, stage = 3, icon_size = 64},
    {item = "caged-dingrits", icon = nil, stage = 3, icon_size = 64},
    {item = "caged-xeno", icon = nil, stage = 3, icon_size = 64},
    {item = "caged-antelope", icon = nil, stage = 3, icon_size = 64},
    {item = "rennea-seeds", icon = nil, stage = 3, icon_size = 64},
    {item = "cridren-seeds", icon = nil, stage = 3, icon_size = 64},
    {item = "digested-rennea-seeds-mk02", icon = nil, stage = 3, icon_size = 64},
    {item = "abraded-rennea-seeds-mk02", icon = nil, stage = 3, icon_size = 64},
    {item = "fish-food-02", icon = nil, stage = 3, icon_size = 64},
    {item = "korlex-food-02", icon = nil, stage = 3, icon_size = 64},
    {item = "mukmoux-food-02", icon = nil, stage = 3, icon_size = 64},
    {item = "phadai-food-01", icon = nil, stage = 3, icon_size = 64},
    {item = "phadai-food-02", icon = nil, stage = 3, icon_size = 64},
    {item = "pheromones", icon = nil, stage = 3, icon_size = 64},
    {item = "gh", icon = nil, stage = 3, icon_size = 64},
    {item = "antiviral", icon = nil, stage = 3, icon_size = 64}
}
